### ISSUE TITLE
Suggest etymology for new names if identical names were already proposed

### ISSUE THREAD

**Issue by uqmchuvo** [seq-code/registry#128]
Propagate the etymology for newly entered species epithets names if they are identical to those present in the registry. We can curate the set of standard translations or have the existing once populating etymology table. This will speed up curation process and avoid manual entering of identical etymologies. Example: **L. gen. n.** soli, of soil

**Comment by lmrodriguezr** [comment]
Hi @uqmchuvo . I believe this is already implemented (if I understand the request correctly).
Try creating a species name with that epithet, set the rank to species, and then go to Edit etymology and click "Automatically fill the etymology". It should already fill-up the etymology.

It also works with compound words. For example, try using _poriticola_ instead of _soli_.

I'll close it now, but please feel free to reopen if you meant something different.

**Comment by uqmchuvo** [comment]
Nice, it works!
One small comment: I think that it is OK to be able to pre-fill it even if the rank wasn't confirmed yet...spelling won't change and rank confirmation can be done after. Any reasons to have this prerequisite for rank confirmation before autofilling the etymology? :) 
Thanks!
